version: "3.2"
services:
  api:
    image: redis-demo:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - "6379:6379"